

---
galaxy_info:
  role_name: patch
  author: Susana Venda
  description: Role to automate RHEL patching
  company: YourCompany
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8

dependencies: []