

---
# Handler to reboot the system if required
- name: Reboot system if needed
  ansible.builtin.reboot:
    msg: "Reboot triggered by patching process"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: ansible_facts['os_family'] == "RedHat" and patch_reboot_required