


---
- name: Update all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Reboot the server if needed
  ansible.builtin.reboot:
    msg: "Rebooting to complete patching"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami