---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: elastic-stack
  name: elastic-stack
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: elastic-stack
    repoURL: https://github.com/alvarolop/otel-to-elastic.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
