---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # Operator installation
  - sub-elasticsearch-eck-operator-certified.yaml
  - ns-elastic.yaml

  # Elasticsearch
  - elasticsearch-elasticsearch.yaml
  - route-elasticsearch.yaml

  # Kibana
  - kibana-kibana.yaml
  - route-kibana.yaml

  # APM Server
  - apmserver-apm-server.yaml
  - route-apm-server.yaml

  # APM Fleet Server
  - sa-elastic-agent.yaml
  - cr-elastic-agent.yaml
  - crb-elastic-agent.yaml

  - agent-fleet-server.yaml
  - agent-elastic-agent.yaml


# Check that the pods run with the correct SCC:
# oc get pod -o go-template='{{range .items}}{{$scc := index .metadata.annotations "openshift.io/scc"}}{{.metadata.name}}{{" scc:"}}{{range .spec.containers}}{{$scc}}{{" "}}{{"\n"}}{{end}}{{end}}'
