name: Assign reviewers

on:
  # pull_request_target is needed instead of just pull_request
  # because repository write permission is needed to assign reviewers
  pull_request_target:

permissions:
  contents: read

jobs:
  assign-reviewers:
    permissions:
      pull-requests: write  # required for assigning reviewers to PRs
    runs-on: ubuntu-latest
    steps:
      - uses: susanavenda/component-owners@main
        with:
          # using this action to request review only (not assignment)
          assign-owners: false
