name: Test image generation

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'

permissions:
  contents: read

jobs:
  build_images:
    if: github.repository == 'susanavenda/observability-swift'
    uses: ./.github/workflows/component-build-images.yml
